version: '2'

services:
  alloy:
    image: grafana/alloy:latest
    user: "0:0"
    restart: unless-stopped
    volumes:
      - ./alloy.alloy:/etc/alloy/config.alloy:ro
      - ./grafana-cloud-key.txt:/grafana-cloud/key:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - alloy-data:/var/lib/alloy/data
    environment:
      MIMIR_URL: ${MIMIR_URL}
      MIMIR_USER: ${MIMIR_USER}
      LOKI_URL: ${LOKI_URL}
      LOKI_USER: ${LOKI_USER}
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    network_mode: "host"

  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped 
    network_mode: "host"

  node-exporter:
    image: quay.io/prometheus/node-exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    pid: "host"
    network_mode: "host"

  dht22-exporter:
    image: sfudeus/dht22-exporter
    restart: unless-stopped
    network_mode: "host"
    privileged: true

volumes:
  alloy-data:

